#pragma once

#include "cameraComponent.hpp"
#include "bladeComponent.hpp"
#include "debugComponent.hpp"
#include "instancedMeshComponent.hpp"
#include "meshComponent.hpp"
#include "transformationComponent.hpp"
#include "laraComponent.hpp"
#include "lightComponent.hpp"
#include "navBlockComponent.hpp"
#include "routeComponent.hpp"
#include "snakeComponent.hpp"
#include "switchComponent.hpp"
#include "autoNavComponent.hpp"
#include "switchBlockComponent.hpp"
#include "metaBlockComponent.hpp"
